services:
    web:
        build:
            context: ./
            dockerfile: ./octane/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        ports:
            - '${APP_PORT:-8000}:8000'
            - '${REDIS_PORT:-6379}:6379'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '${VITE_REVERB_PORT:-8080}:${VITE_REVERB_PORT:-8080}'
            - '443:443'
            - '443:443/udp'
        environment:
            SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --host=localhost --port=443 --admin-port=2019 --https"
            XDG_CONFIG_HOME:  /var/www/html/config
            XDG_DATA_HOME:  /var/www/html/data
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-debug}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './:${WORKDIR}'
            - './vendor/:${WORKDIR}/vendor'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - minio
            - mailpit
        extra_hosts:
            - 'host.docker.internal:host-gateway'
    mysql:
        image: 'mysql/mysql-server:${MYSQL_VERSION:-8.0}'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - '${DB_VOLUME_LOCAL:-./database/mysql-test-data}:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - '${REDIS_VOLUME_LOCAL:-./database/redis-data}:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: '${MINIO_ROOT_USER:-sail}'
            MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD:-password}'
        volumes:
            - '${MINIO_VOLUME_LOCAL:-./storage/minio-data}:/data'
        networks:
            - sail
        command: 'minio server /data/minio --console-address ":${FORWARD_MINIO_CONSOLE_PORT}"'
        healthcheck:
            test:
                - CMD
                - curl
                - '-f'
                - 'http://localhost:${FORWARD_MINIO_PORT}/minio/health/live'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        volumes:
            - '${MP_VOLUME_LOCAL:-./storage/mail-data}:/data'
        networks:
            - sail
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: pma
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: '${DB_USERNAME}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '8081:80'
        networks:
            - sail
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        container_name: meilisearch
        restart: unless-stopped
        ports:
            - '7720:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS}'
            MEILI_NO_SENTRY: '${MEILISEARCH_NO_SENTRY}'
            MEILI_MASTER_KEY: '${MEILISEARCH_KEY}'
        networks:
            - sail
        volumes:
            - './meilisearch-data:/meilisearch-data'
    memcached:
        image: 'memcached:alpine'
        ports:
            - '${FORWARD_MEMCACHED_PORT:-11211}:11211'
        networks:
            - sail
networks:
    sail:
        driver: bridge
