
services:
    web:
        build:
            context: .
            dockerfile: ./octane/Dockerfile
        ports:
            - '${APP_PORT:-8000}:8000'
            - '${REDIS_PORT:-6379}:6379'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '${VITE_REVERB_PORT:-8080}:${VITE_REVERB_PORT:-8080}'
            - '443:443'
            - '443:443/udp'
        depends_on:
            - mysql
            - redis
            - minio 
            - meilisearch
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - netisu
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT:-8000}/up"] # Implement a health check endpoint for Octane
            interval: 5s
            timeout: 3s
            retries: 3
    
    mysql:
        image: 'mysql/mysql-server:${MYSQL_VERSION:-8.0}'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
        volumes:
            - '${DB_VOLUME_LOCAL:-./database/mysql-test-data}:/var/lib/mysql'
        networks:
            - netisu
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - '${REDIS_VOLUME_LOCAL:-./database/redis-data}:/data'
        networks:
            - netisu
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: '${MINIO_ROOT_USER:-sail}'
            MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD:-password}'
        volumes:
            - '${MINIO_VOLUME_LOCAL:-./storage/minio-data}:/data'
        command: 'minio server /data/minio --console-address ":${FORWARD_MINIO_CONSOLE_PORT}"'
        networks:
            - netisu
        healthcheck:
            test:
                - CMD
                - curl
                - '-f'
                - 'http://localhost:${FORWARD_MINIO_PORT}/minio/health/live'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - netisu
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        container_name: meilisearch
        restart: unless-stopped
        ports:
            - '7720:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS}'
            MEILI_NO_SENTRY: '${MEILISEARCH_NO_SENTRY}'
            MEILI_MASTER_KEY: '${MEILISEARCH_KEY}'
        volumes:
            - './meilisearch-data:/meilisearch-data'
        networks:
            - netisu

networks:
    netisu:
        driver: bridge
