/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.telescope": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "minify.assets": [
        {
            "name": "file",
            "required": false
        }
    ],
    "cashier.payment": [
        {
            "name": "id",
            "required": true
        }
    ],
    "cashier.webhook": [],
    "passport.token": [],
    "passport.authorizations.authorize": [],
    "passport.token.refresh": [],
    "passport.authorizations.approve": [],
    "passport.authorizations.deny": [],
    "passport.tokens.index": [],
    "passport.tokens.destroy": [
        {
            "name": "token_id",
            "required": true
        }
    ],
    "passport.clients.index": [],
    "passport.clients.store": [],
    "passport.clients.update": [
        {
            "name": "client_id",
            "required": true
        }
    ],
    "passport.clients.destroy": [
        {
            "name": "client_id",
            "required": true
        }
    ],
    "passport.scopes.index": [],
    "passport.personal.tokens.index": [],
    "passport.personal.tokens.store": [],
    "passport.personal.tokens.destroy": [
        {
            "name": "token_id",
            "required": true
        }
    ],
    "sanctum.csrf-cookie": [],
    "swagger.index": [],
    "swagger.oauth2-redirect": [],
    "swagger.json": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "api.": [],
    "api.messaging.": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.messaging.fetchMessages": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.spaces.": [
        {
            "name": "spaceId",
            "required": true
        },
        {
            "name": "rankId",
            "required": true
        }
    ],
    "api.search": [],
    "api.avatar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.user.": [],
    "api.user.name-availability": [],
    "api.user.email-validate": [],
    "api.user.password-validate": [],
    "api.user.profile-data": [
        {
            "name": "username",
            "required": true
        }
    ],
    "api.user.online": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.user.inventory": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.user.currently-wearing": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.user.status": [],
    "api.user.avatar": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.user.follow": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.user.unfollow": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.dashboard.": [],
    "api.dashboard.statuses": [],
    "api.notif.": [],
    "api.notif.read-all": [],
    "api.item.rerender": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.store.": [],
    "api.store.items": [
        {
            "name": "category",
            "required": true
        }
    ],
    "api.store.event.items": [
        {
            "name": "eventId",
            "required": true
        }
    ],
    "api.store.purchase": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "currencyType",
            "required": true
        }
    ],
    "api.avatar.": [],
    "api.avatar.items": [
        {
            "name": "category",
            "required": true
        }
    ],
    "api.avatar.wearing-hats": [],
    "api.avatar.wear-item": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "slot",
            "required": true
        }
    ],
    "api.avatar.remove-item": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "slot",
            "required": true
        }
    ],
    "api.settings.": [],
    "api.settings.uploadBanner": [],
    "api.settings.uploadProfilePicture": [],
    "api.settings.changeCountry": [
        {
            "name": "country",
            "required": true
        }
    ],
    "api.settings.changePassword": [],
    "api.rss": [],
    "api.thumbnails": [
        {
            "name": "type",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "api.admin.enableMaintenance": [],
    "api.admin.disableMaintenance": [],
    "api.admin.gift-item": [
        {
            "name": "itemID",
            "required": true
        },
        {
            "name": "userID",
            "required": true
        }
    ],
    "api.admin.purge": [
        {
            "name": "type",
            "required": true
        },
        {
            "name": "assetId",
            "required": true
        }
    ],
    "maintenance.page": [],
    "maintenance.authenticate.password": [],
    "maintenance.exit": [],
    "leaderboard.page": [],
    "my.money.page": [],
    "my.money.convert-currency": [],
    "my.dashboard.page": [],
    "my.dashboard.validate": [],
    "user.page": [],
    "user.profile": [
        {
            "name": "username",
            "required": true
        }
    ],
    "user.settings.page": [],
    "user.settings.update": [],
    "user.settings.destroy": [],
    "promocodes.page": [],
    "promocodes.redeem": [],
    "avatar.page": [],
    "avatar.update": [],
    "forum.": [],
    "forum.page": [
        {
            "name": "id",
            "required": true
        }
    ],
    "forum.your.posts": [],
    "forum.post": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "slug",
            "required": true
        }
    ],
    "forum.create.page": [
        {
            "name": "id",
            "required": true
        }
    ],
    "forum.create.validate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "forum.reply.validate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "chat.messages": [
        {
            "name": "userID",
            "required": true
        }
    ],
    "chat.validate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "acheivements": [],
    "notification.page": [],
    "notification.view": [
        {
            "name": "id",
            "required": true
        }
    ],
    "auth.logout": [],
    "auth.language": [
        {
            "name": "language",
            "required": true
        }
    ],
    "auth.login.google": [],
    "auth.login.google.validation": [],
    "auth.login.page": [],
    "auth.login.validate": [],
    "auth.login.metamask": [],
    "auth.login.metamask.validation": [],
    "auth.register.page": [],
    "auth.register.validate": [],
    "auth.forgot.page": [],
    "auth.forgot.password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "auth.forgot.password.email": [],
    "password.confirm.form": [],
    "password.confirm": [],
    "Welcome": [],
    "games.page": [],
    "games.game": [],
    "removed": [],
    "store.page": [],
    "store.create.page": [],
    "store.create.validate": [],
    "store.item": [
        {
            "name": "id",
            "required": true
        }
    ],
    "store.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "store.edit.validate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "store.purchase": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "currencyType",
            "required": true
        }
    ],
    "membership.page": [],
    "membership.purchase": [
        {
            "name": "id",
            "required": true
        }
    ],
    "develop.page": [],
    "develop.create.page": [],
    "develop.create.validate": [],
    "develop.item": [
        {
            "name": "id",
            "required": true
        }
    ],
    "develop.purchase": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "currencyType",
            "required": true
        }
    ],
    "spaces.page": [],
    "spaces.create.page": [],
    "spaces.create.validate": [],
    "spaces.membership": [
        {
            "name": "id",
            "required": true
        }
    ],
    "spaces.view": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "slug",
            "required": true
        }
    ],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "admin.page": [],
    "admin.users.page": [],
    "admin.users.manage-user": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.users.gift-user": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.items.page": [],
    "admin.items.manage-item": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.items.create.create-item": [],
    "admin.items.create.validate": [],
    "admin.messaging.page": [],
    "admin.messaging.validate": [],
    "admin.reports.page": [],
    "admin.reports.view": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.assets.approve": []
}
}
export {};
