#!/usr/bin/env bash


if ! grep -q "^APP_KEY=" .env; then
    echo "Generating application key..."
    php /var/www/html/artisan key:generate --ansi
fi

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi